Updated annotators to 1.5.0, removed annotran which is now dead in th…
BirkbeckCTP/annotators pull request #2
Opened 2023-06-23 15:28 UTC by ajrbyers

…e water.

2024-03-15 12:37 UTC, mauromsl requested changes
just one comment inline

2024-03-15 12:37 UTC, mauromsl commented on views.py
> +    enable_hypothesis = setting_handler.get_setting(
This should use `setting_handler.get_plugin_setting` to avoid duplicating the logic here

2024-04-18 08:24 UTC, mauromsl approved these changes

2024-04-18 12:20 UTC, joemull approved these changes

2024-04-18 12:20 UTC, merged

2024-04-18 12:21 UTC, joemull commented
@ajrbyers did this close #1 ?

2024-04-18 12:24 UTC, ajrbyers commented
> @ajrbyers did this close #1 ?

It did. Nice. I want to use this plugin for my project-time work to allow a private annotator so althoug we could rename it "hypothesis" I think might be fine to leave it for now.